name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-dev build-essential libssl-dev libffi-dev python3-venv libltdl-dev libffi-dev libssl-dev libbz2-dev libsqlite3-dev libreadline-dev zlib1g-dev autoconf automake libtool pkg-config zip unzip

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-sistema-ventas
          path: bin/*.apk
